# GitHub Pages Configuration
title: Dungeon Destiny Dashboard
description: Interactive development management dashboard for Dungeon Destiny tabletop RPG Phase 2 implementation
baseurl: ""
url: "https://odaat1991.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files
exclude:
  - README.md
  - .gitignore
  - node_modules/
  - vendor/

# Include files
include:
  - _pages

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom variables
author: Martin Acosta
email: odaat1991@gmail.com
github_username: odaat1991

# SEO and social
twitter_username: 
facebook_username: 
linkedin_username: 

# Google Analytics (optional)
# google_analytics: 

# Project specific
project:
  name: "Dungeon Destiny"
  phase: "Phase 2 - Core Systems Implementation" 
  version: "0.2.0-alpha"
  start_date: "2025-10-07"
  target_date: "2025-12-30"